hmcts/rpe-pdf-service

- pdf-generator/src/main/java/uk/gov/hmcts/reform/cmc/pdf/generator/HTMLTemplateProcessor.java
- src/integrationTest/java/uk/gov/hmcts/reform/cmc/pdf/service/integration/ResponseCodesTest.java
https://tools.hmcts.net/jira/browse/ROC-2062
n/a
```
[ ] Yes
[x] No
```
> ROC-2062: Fail PDF creation without necessary data

- Jenkinsfile
Reverts hmcts/cmc-pdf-service#9
> Revert "Disable automatic deployment to DEMO env"

- Dockerfile
None
Using Alpine will make our image smaller and faster to download.
```
[ ] Yes
[x] No
```
> Use Alpine image as base image

- README.md
- build.gradle
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/HTMLTemplateProcessor.java
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/HTMLToPDFConverter.java
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/PDFGenerator.java
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/exception/MalformedTemplateException.java
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/exception/PDFGenerationException.java
- src/integrationTest/java/uk/gov/hmcts/reform/pdf/service/integration/GeneratedPDFContentTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/pdf/service/integration/ResponseCodesTest.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/PDFServiceApplication.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/config/JacksonConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/config/PDFServiceConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/PDFGenerationEndpoint.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/exception/ExceptionHandling.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/exception/InvalidArgumentException.java
- src/test/java/uk/gov/hmcts/reform/pdf/service/endpoint/PDFGenerationEndpointArgumentsHandlingTest.java
Service will be shared across many organisations.
JIRA: RPE-151
```
[ ] Yes
[x] No
```
> Remove CMC from namespaces

- .travis.yml
Fixing incorrect syntax of if statement in travis configuration file
```
[ ] Yes
[x] No
```
> Fix bash syntax of if statement

- .travis.yml
Solve couple human problems:
- remove unnecessary evil of bash syntax inside travis configuration file
- make configuration file more readable
```
[ ] Yes
[x] No
```
> Use travis test function to replace bash syntax

- build.gradle
CMC reference sneaked in within my previous change. This PR removes it.
```
[ ] Yes
[X] No
```
> Remove CMC reference

- README.md
- build.gradle
- src/main/java/uk/gov/hmcts/reform/pdf/service/config/DeprecatedApiConfiguration.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/PDFGenerationEndpoint.java
- src/test/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/DeprecatePDFGenerationEndpointTest.java
https://tools.hmcts.net/jira/browse/RPE-161
Old API has been scheduled for decommission on 8th Feb 2018.
```
[ ] Yes
[x] No
```
> Deprecate old api

- Jenkinsfile
> Send pdf service build data to influxdb

- Jenkinsfile
None
This PR stops automatic deployments to CMC environment as component is supposed to be deployed in shared location. 
```
[ ] Yes
[x] No
```
> Stop deploying service to CMC environment on build

- build.gradle
- ruleset.xml
- src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/PDFGenerationEndpoint.java
- src/test/java/uk/gov/hmcts/reform/pdf/service/domain/GeneratePdfRequestTest.java
Another tool that adheres to standardised coding rules. Run `./gradlew check` to get reports.
```
[ ] Yes
[x] No
```
> Enable pmd

- build.gradle
https://tools.hmcts.net/jira/browse/ROC-1105
Use latest java-logging to make use of updated request tracing features.
```
[ ] Yes
[X] No
```
> Update java-logging version

- docker-compose.yml
None
This PR uses the same Docker repository as the one used by Jenkins when image is being built.
```
[ ] Yes
[x] No
```
> Update docker-compose.yml to use new repository path

- Jenkinsfile_parameterized
> Use 'saat' for default environment pipeline parameter

- build.gradle
- src/main/resources/application.yml
> Add App Insights dependencies

- infrastructure/main.tf
- infrastructure/variables.tf
Provide the `subscription` input variable which now expected by `moj-module-webapp`. 
```
[ ] Yes
[X] No
```
> Align with updated Terraform module

- HTMLToPDFTestForm.html
Make utf-8 chars render properly...
> Set content type in test form

- infrastructure/main.tf
- infrastructure/variables.tf
none
Allows PR envs to be closed after PR is merged
```
[ ] Yes
[ ] No
```
> Add common tags

- infrastructure/main.tf
The branch no longer exists.
Also migrating to the new repo.
> Use latest webapp tf module

- Jenkinsfile_nightly
... to run owasp dependency check
> Set up nightly build

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RPE-644
Step  1 of migrating to spring boot 2: suppress vulnerability so the next PRs can be merged, the last PR will remove this suppression
```
[ ] Yes
[ ] No
```
> RPE-644 Suppress vulnerability

- .dockerignore
- Dockerfile
- docker-compose.yml
https://tools.hmcts.net/jira/browse/RPE-644
Update to newest base image and improve build time and fix docker-compose file
```
[ ] Yes
[ ] No
```
> Update to newest base image and improve build time

- charts/cmc-pdf-service/requirements.yaml
Update the Java chart dependency so we can use the new inter-pod anti-affinity feature
```
[ ] Yes
[x] No
```
> update Java chart dependency

- charts/cmc-pdf-service/Chart.yaml
forgot to bump chart version to get it published
```
[ ] Yes
[ x] No
```
> bump chart version

- build.gradle
Fixing dependency issue
NA
Fixing dependency issue
```
[ ] Yes
[x] No
```
> Fixing dependency issue

- charts/cmc-pdf-service/Chart.yaml
- charts/cmc-pdf-service/requirements.yaml
- charts/cmc-pdf-service/values.aat.template.yaml
- charts/cmc-pdf-service/values.preview.template.yaml
- charts/cmc-pdf-service/values.template.yaml
https://tools.hmcts.net/jira/browse/RPE-914
Refactor preview configurations and bumping java-chart
```
[ ] Yes
[x] No
```
> Refactor preview configurations and bumping java-chart

- charts/cmc-pdf-service/Chart.yaml
- charts/cmc-pdf-service/requirements.yaml
Updating Java chart
Updating java chart as there is an with 2.0.3 env tpl function
```
[ ] Yes
[x] No
```
> Updating Java chart

- charts/cmc-pdf-service/Chart.yaml
- charts/cmc-pdf-service/requirements.yaml
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/109
Bump java chart version
```
[ ] Yes
[x] No
```
[AB#109](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/109)
> bump java chart version AB#109

- build.gradle
- pdf-generator/build.gradle
See: https://build.platform.hmcts.net/view/Platform/job/HMCTS_Nightly_Platform/job/rpe-pdf-service/job/master/70/console
```
[ ] Yes
[x] No
```
> Fix CVE-2019-12086

- build.gradle
Signed-off-by: Karim Lawani <k7lawani@gmail.com>
[AB#171](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/171)
Fixe JaCoCo warnings due to Deprecated settings
```
[ ] Yes
[x ] No
```
> fix JaCoCo settings warnings

- build.gradle
- pdf-generator/build.gradle
[[AB#236](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/236)]
```
[ ] Yes
[x] No
```
> Migrate to owasp 5

- build.gradle
- pdf-generator/build.gradle
> updgrade jackson databind

- build.gradle
- config/checkstyle/checkstyle.xml
> Bumping checkstyle

- Jenkinsfile_CNP
> Preparing to AKS Prod

- Jenkinsfile_CNP
Reverts hmcts/rpe-pdf-service#122
> Revert "Preparing to AKS Prod"

- docker-compose.yml
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/HTMLTemplateProcessor.java
- pdf-generator/src/main/java/uk/gov/hmcts/reform/pdf/generator/HTMLToPDFConverter.java
- pdf-generator/src/test/java/uk/gov/hmcts/reform/pdf/generator/HTMLToPDFConverterTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/pdf/service/GeneratedPDFContentV2Test.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/PDFGenerationEndpoint.java
- src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/v2/PDFGenerationEndpointV2.java
> Stop converting string to byte and back to string

- charts/cmc-pdf-service/Chart.yaml
- charts/cmc-pdf-service/requirements.yaml
> Upgrade to latest java chart.

- Jenkinsfile_CNP
> Switch back to jenkins library master branch

- Jenkinsfile_CNP
> Trigger rebuild

- Jenkinsfile_CNP
[[AB#641](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/641)]
```
[ ] Yes
[x] No
```
> Test jenkins library test image generation

- config/owasp/suppressions.xml
Deleted expired suppression
```
[ ] Yes
[x] No
```
> Suppress owasp issue temporarily

- Jenkinsfile_CNP
- build.gradle
- config/owasp/suppressions.xml
> Update dependencies. Clean up suppressions.

- build.gradle
- charts/rpe-pdf-service/Chart.yaml
- charts/rpe-pdf-service/values.yaml
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
- pdf-generator/build.gradle
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/PDFGenerationEndpointArgumentsHandlingTest.java
> Appinsights from secret

- charts/rpe-pdf-service/Chart.yaml
- charts/rpe-pdf-service/values.yaml
> change ingress to rpe

- .github/renovate.json
- renovate.json
> fix renovate

- Dockerfile
- build.gradle
> Update to java 11

- Jenkinsfile_CNP
- build.gradle
- config/owasp/suppressions.xml
- src/contractTest/java/uk/gov/hmcts/reform/pdf/service/endpoint/v2/PDFGenerationEndpointV2ProviderTest.java
> TA-85: Provider test for divorce cms

- build.gradle
- charts/rpe-pdf-service/Chart.yaml
- charts/rpe-pdf-service/values.yaml
- pdf-generator/build.gradle
- src/main/resources/application.yml
- src/main/resources/bootstrap.yaml
> Spring 2.4 upgrade with configtree

- .dockerignore
- Dockerfile
- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/DTSPO-5982
Added multi-architecture ACR Task template.
```
[ ] Yes
[X] No
```
> Added multi-architecture ACR Task template.

- build.gradle
- charts/rpe-pdf-service/Chart.yaml
- config/owasp/suppressions.xml
Bumped tomcat and java
Bumped tomcat version based on mitigation here https://lists.apache.org/thread/k04zk0nq6w57m72w5gb0r6z9ryhmvr4k and affected versions here https://www.cve.org/CVERecord?id=CVE-2022-34305
```
[ ] Yes
[ ] No
```
> Upgrade java version

- .github/CODEOWNERS
- charts/rpe-pdf-service/Chart.yaml
DTSPO-8276
- Create CODEOWNERS file
```
[ ] Yes
[X] No
```
> DTSPO-8276 - Create CODEOWNERS file

- build.gradle
> upgrade owasp plugin

- config/owasp/suppressions.xml
Suppress CVE-2022-45688
```
[ ] Yes
[x] No
```
> Suppress false positive - CVE-2022-45688

- .github/dependabot.yml
- .github/renovate.json
Rebased on spring-boot-template
> Switch to renovate only

- Dockerfile
Getting 404 on startup probe
Similar issue in NFD and WA was solved by updating this
```
[ ] Yes
[x] No
```
> Update app insights in Dockerfile

- build.gradle
- charts/rpe-pdf-service/Chart.yaml
- config/owasp/suppressions.xml
DTSPO-15411
DTSPO-15411 - chart update for Workload Identity update
```
[ ] Yes
[X ] No
```
> DTSPO-15411 - chart update for Workload Identity update

- config/owasp/suppressions.xml
Previous merge seems to have overwritten!
> Suppress dependancies which cannot be upgraded

- config/owasp/suppressions.xml
> Extending supressions

- config/owasp/suppressions.xml
> Changing expiry date for supressions
